stages:
  - build
  - test
  - sonar_analysis

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  SONAR_HOST_URL: "http://192.168.100.201:9000"

cache:
  paths:
    - .m2/repository

before_script:
  - echo "Using Maven version:"
  - mvn -v

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

sonarqube:
  stage: sonar_analysis
  script:
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar -Dsonar.projectKey=AppSpringboot -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN
  only:
    - main
  allow_failure: true
